### ISSUE TITLE
Decide on npm Package Naming

### ISSUE THREAD

**Issue by bradley-holt** [ibm-watson-data-lab/shopping-list-model-js#8]
Options are:

* `@ibm-shopping-list/model` (what I have now; puts this app in its own scope)
* `@ibm/shopping-list-model` (could be good if this gets published as a Developer Journey)
* `@ibm-wdp/shopping-list-model` (uses our existing `ibm-wdp` scope)
* `ibm-wdp-shopping-list-model` (doesn't use scoping at all)

**Comment by isc-rsingh** [comment]
I vote for `@ibm-wdp/shopping-list-model` @bradley-holt

**Comment by bradley-holt** [comment]
@rajrsingh I had thought I had seen packages from us before using the `@ibm-wdp` scope. However, I can't seem to find these now. Does that change your opinion if I'm wrong about this scope already being in use?

**Comment by bradley-holt** [comment]
After further reflection, I'm thinking of going with:

`ibm-shopping-list-model`

My reasoning:

* I don't see a lot of usage yet of scoped packages. For example, PouchDB does not use scoped packages. Also, I seem to be mistaken about our team having used scoped packages in the past as I now cannot find any examples of this.
* One goal of these demos is to be used as Developer Journeys. Scoping it at the IBM level (versus IBM WDP) makes more sense given this context. This also avoids awkwardness in the event of a re-org or if these apps are used as reference implementations for other technologies.

The apps would then follow a `ibm-shopping-list-app-*` naming convention. For example:

* `ibm-shopping-list-app-vanillajs-pouchdb`
* `ibm-shopping-list-app-polymer-pouchdb`
* `ibm-shopping-list-app-react-pouchdb`
* `ibm-shopping-list-app-preact-pouchdb`
* `ibm-shopping-list-app-vuejs-pouchdb`
* `ibm-shopping-list-app-emberjs-pouchdb`
* `ibm-shopping-list-app-react-native-pouchdb`
* `ibm-shopping-list-app-react-native-cloudant-sync`
* `ibm-shopping-list-app-ionic-pouchdb`
* `ibm-shopping-list-app-ionic-cloudant-sync`
* `ibm-shopping-list-app-ionic-cordova-pouchdb`
* `ibm-shopping-list-app-ionic-cordova-cloudant-sync`
* `ibm-shopping-list-app-electron-pouchdb`

Note that the Swift and Kotlin implementations would not be represented as npm packages, so are not listed above.

**Comment by bradley-holt** [comment]
Changed in 2c69d876ccc9ecd69319f9e7ced5985bbc6d376b.
